#!/usr/bin/env bash

echo "[INFO] Running pre-commit checks..."

# check formatting
make fmt_check

# check if format check failed
if [ $? -ne 0 ]; then
    echo "[INFO] Run: make fmt"
    exit 1
fi

echo "[OK] Pre-commit checks passed"