// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteContainer(arg1) {
  return window['go']['backend']['App']['DeleteContainer'](arg1);
}

export function FindContainer(arg1) {
  return window['go']['backend']['App']['FindContainer'](arg1);
}

export function GetAppInfo() {
  return window['go']['backend']['App']['GetAppInfo']();
}

export function GetContainerLogs(arg1) {
  return window['go']['backend']['App']['GetContainerLogs'](arg1);
}

export function GetDockerStatus() {
  return window['go']['backend']['App']['GetDockerStatus']();
}

export function GetService(arg1) {
  return window['go']['backend']['App']['GetService'](arg1);
}

export function GetServiceCatalog() {
  return window['go']['backend']['App']['GetServiceCatalog']();
}

export function IsPortAvailable(arg1) {
  return window['go']['backend']['App']['IsPortAvailable'](arg1);
}

export function LaunchContainer(arg1) {
  return window['go']['backend']['App']['LaunchContainer'](arg1);
}

export function ListAllContainer() {
  return window['go']['backend']['App']['ListAllContainer']();
}

export function Log(arg1, arg2) {
  return window['go']['backend']['App']['Log'](arg1, arg2);
}

export function RestartContainer(arg1) {
  return window['go']['backend']['App']['RestartContainer'](arg1);
}

export function StartContainer(arg1) {
  return window['go']['backend']['App']['StartContainer'](arg1);
}

export function StopContainer(arg1) {
  return window['go']['backend']['App']['StopContainer'](arg1);
}
