// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {docker} from '../models';
import {backend} from '../models';
import {network} from '../models';

export function CloseTerminal(arg1:string):Promise<void>;

export function DeleteContainer(arg1:string):Promise<void>;

export function FindContainer(arg1:string):Promise<docker.Container>;

export function GetAppInfo():Promise<backend.AppInfo>;

export function GetContainerLogs(arg1:string):Promise<string>;

export function GetDockerStatus():Promise<docker.DockerStatus>;

export function GetService(arg1:string):Promise<backend.Service|boolean>;

export function GetServiceCatalog():Promise<Array<backend.Service>>;

export function IsPortAvailable(arg1:number):Promise<network.PortCheckResponse>;

export function LaunchContainer(arg1:backend.StartServiceRequest):Promise<void>;

export function ListAllContainer():Promise<Array<docker.Container>>;

export function Log(arg1:backend.LogLevel,arg2:string):Promise<void>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function RestartContainer(arg1:string):Promise<void>;

export function SendTerminalInput(arg1:string,arg2:string):Promise<void>;

export function StartContainer(arg1:string):Promise<void>;

export function StartTerminal(arg1:string):Promise<string>;

export function StopContainer(arg1:string):Promise<void>;
